version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  hollandaise-api:
    container_name: hollandaise-api
    tty: true
    init: true # Properly handles running as PID 1 inside a container. Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "node", "/usr/src/app/healthcheck.js"] # Check health endpoint for healthy service.
      interval: 30s # Perform the health check every 30 seconds.
      timeout: 10s # Consider the health check a failure if it takes more than 10 seconds.
      retries: 5 # Retry the health check up to 5 times before considering the container unhealthy.
    build:
      context: ./src/backend
      dockerfile: .docker/Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - DEBUG=${DEBUG:-false}
      - PORT=${BACKEND_PORT:-9002}
      - FRONTEND_PORT=${FRONTEND_PORT:-9000}
      - PGHOST=${DATABASE_HOST:-hollandaise-database} # Name of the database container.
      - PGUSER=${DATABASE_USER:-postgres}
      - PGPASSWORD=${DATABASE_PASSWORD:-postgres}
      - PGDATABASE=${DATABASE_NAME:-project}
      - PGPORT=5432
      - SSO_AUTH_SERVER_URL=${SSO_AUTH_SERVER_URL}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
    networks:
      - hollandaise-network
    ports:
      - ${BACKEND_PORT:-9002}:9002
    depends_on:
      hollandaise-database:
        condition: service_healthy
  
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  hollandaise-frontend:
    container_name: hollandaise-frontend
    tty: true
    restart: on-failure
    build:
      context: ./src/frontend
      target: prod
      dockerfile: .docker/Dockerfile
    networks:
      - hollandaise-network
    ports:
      - ${FRONTEND_PORT:-9000}:9000
    depends_on:
      hollandaise-api:
        condition: service_healthy

  #############################################################################################
  ###                                       Database                                        ###
  #############################################################################################
  hollandaise-database:
    container_name: hollandaise-database
    tty: true
    image: postgres:13.9
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"] # Check if PostgreSQL is ready.
      interval: 15s # Perform the health check every 15 seconds.
      timeout: 5s # Consider the health check a failure if it takes more than 5 seconds.
      retries: 5 # Retry the health check up to 5 times before considering the container unhealthy.
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-project}
    networks:
      - hollandaise-network
    ports:
      - ${DATABASE_PORT:-9005}:5432
    volumes:
      - database-data:/var/lib/postgresql/data # Named volume binded to Postgres' data store directory.

volumes:
  database-data:
    driver: local # Stores the volume data on the host machine's file system.

networks:
  hollandaise-network:
    driver: "bridge"
