name: Build Hollandiase API

on:
  push:
    branches: [ main ]
    paths:
      - TBD - August 16
  workflow_dispatch:
  
jobs:

  Hollandaise-API-Build-Tag-Push:

  Hollandaise-API-Deploy:

  Hollandaise-API-Healthcheck:

  Hollandaise-API-Success-Notify:
