name: Build Hollandiase Frontend

on:
  push:
    branches: [ main ]
    paths:
      - TBD - August 16
  workflow_dispatch:
  
jobs:

  Hollandaise-Frontend-Build-Tag-Push:

  Hollandaise-Frontend-Deploy:

  Hollandaise-Frontend-Healthcheck:

  Hollandaise-Frontend-Success-Notify:
